import Head from 'next/head'
import Image from 'next/image'
import HomePage from "@/pages_content/Home"
import axios from 'axios'
import { BASE_URL } from '@/constants'

// export async function getServerSideProps (context) {
//   try{
//       const result = await axios.get(BASE_URL+"api/product/listing?is-dashboard=true")
//       // const result2 = await axios.get(BASE_URL+"api/product/listing?offset=0&limit=12&category-id=&search=")
//       return {
//           props: {
//               // shop: result2.data.payload,
//               shop: [],
//               data: result.data.payload,
//               description: result.data.description,
//               error: null
//           }
//       }
//   }
//   catch(e){
//       console.log(e)
//       return {
//           props: {
//               shop: [],
//               data: null,
//               description: e.response ? JSON.stringify(e.response.data.description) : "Network Error",
//               error: true
//           }
//       }
//   }
// }

export default function Home(props) {
  return (
    <>
      <Head>
        <title>PRO WEARS - SHOP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage {...props}/>
    </>
  )
}
